### ISSUE TITLE
Dynamically changing the duration attribute of the component for historical data causes an error

### ISSUE THREAD

**Issue by pcsandford** [Rise-Vision/rise-financial#28]
### What currently happens

When  the `type` attribute is set to `"historical"` and the `duration` attribute is changed dynamically e.g. using jQuery to change it from `"Day"` to `"1M"` the component does not return the correct data when `financial.go()` is called and instead produces this error:
![screen shot 2017-02-27 at 2 02 36 pm](https://cloud.githubusercontent.com/assets/8008948/23380459/e2b567f8-fd08-11e6-8371-4e80739951c5.png)

### What should happen

It should be possible to change the `duration` attribute and call `financial.go()` to get a new set of data.

### Steps to reproduce 

1. Set up the component for historical data and set the `duration = "Day"`
2. Using JS or jQuery change the `duration` attribute to `"1M"`
3. The chart will not update with the month data and will show the above error instead

@stulees FYI

Thanks!

**Comment by stulees** [comment]
@pcsandford As we spoke about before, dynamically changing `duration` wasn't considered and I'm refactoring to allow for that. 

However, I'm unable to replicate the error you've seen in dev console. I temporarily modified the demo to add a "1 Month" button to trigger changing duration and calling go() and at no point afterwards is there an error. 

Are you able to consistently replicate it? Are you only able to replicate it with Rise Cache running? Thanks

**Comment by pcsandford** [comment]
@stulees I am able to get the error each time I try to change the value via the button while rise-cache is running. If I turn off rise-cache the error no longer shows. Were you able to get return different data using the button in the demo? If so it could be that there is something wrong with my code rather than the component itself. 

These are the errors showing in rise-cache:
<img width="795" alt="screen shot 2017-02-28 at 7 19 38 pm" src="https://cloud.githubusercontent.com/assets/8008948/23440616/ecea39b4-fdea-11e6-8ed5-05ab4b60db08.png">


Thanks!

**Comment by stulees** [comment]
@pcsandford Ah, those errors are making more sense now. We recently discovered an issue from monitoring Rise Cache reliability and saw a lot of error logs stating "Could not save financial data". We know what the problem is and have an active card to fix that, so it's definitely a separate issue.

**Comment by pcsandford** [comment]
@stulees ah ok, sorry for not including that screenshot in my initial comment! Are you currently working on the refactoring? I will be out later this morning but will check back online later for any validation. Thanks!

**Comment by stulees** [comment]
@pcsandford Currently doing the refactoring to enable dynamic `duration` changing, will @ mention you on the Trello card when ready to validate, cheers.

**Comment by pcsandford** [comment]
@stulees validated and looks good. Thanks!
