### ISSUE TITLE
Error when more than one instance of component is used

### ISSUE THREAD

**Issue by pcsandford** [Rise-Vision/rise-financial#31]
### What currently happens

When you add more than one instance of the component to the html you get the following error:
![screen shot 2017-03-06 at 1 47 14 pm](https://cloud.githubusercontent.com/assets/8008948/23626730/eb32fa30-027b-11e7-817b-a1710ebcf013.png)

### What should happen

It should be possible to add more than one instance of the component to an html file, both for current and historical data.

###Steps to recreate

1. Add two instances of the component to an html file.
2. Even if only one instance is referenced in the JS, the above error will appear in the console.

**Comment by alanclayton** [comment]
Fix deployed.
