### ISSUE TITLE
All financial data on legacy marketwalls is being returned with sample figures (1234.5)

### ISSUE THREAD

**Issue by PatrickA-RiseVision** [Rise-Vision/rise-financial#62]
### What is the expected behavior?
Financial instruments return accurate financial data.

### What is the actual behavior?
Financial data is returned on marketwalls that rely on the financial selector as dummy values, i.e. $1234.50.
Financial templates work as expected.

### What steps can be taken to replicate the problem?
Show financial data using a legacy marketwall design.
I have an example of this I can share.

**Comment by santiagonoguez** [comment]
@olegrise could this be the same as the remaining server side action for https://github.com/Rise-Vision/html-template-library/issues/2246 ?

**Comment by santiagonoguez** [comment]
Electron player release has completed, so I'm finally closing the issue.
