### ISSUE TITLE
Displays with several Financial presentations sporadically go blank.

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/rise-financial#64]
#Expected Behaviour
As a user I expect the financial placeholder data to show up in the financial templates Rise offers, regardless of how many I add to my schedule, or their duration in the schedule.

#Actual Behaviour
Some presentations will show blank financial data, and appear to show the default background / logo, like they are not loading up financial content or branding info at all. 

From first appearances, this appears to be due to capacity. In all cases I have tested this, they are on weaker machines, with several presentation templates, all showing for 45 - 55 seconds each.

#Client Instance in Production:
https://apps.risevision.com/schedules/details/231759db-2c19-454b-bfbc-1d382c4af185?cid=f4f293e6-cd68-4964-80e9-11ee945bfdaa

https://apps.risevision.com/schedules/details/93633362-5af5-47f4-8756-6b4be052c9af?cid=46e213a2-6dec-4d95-a672-98f47a5a98c7

**Comment by robb-price** [comment]
After a conversation with Mat, I think the issue may actually be tied to data requests. Even in Editor, you can easily recreate this: https://drive.google.com/file/d/1ukiBx3OKg7F6IaqlMa5m3sjWymbZ1C3E/view?usp=drivesdk

**Comment by stulees** [comment]
@robb-price Closing as per escalated channel update, fixed with https://github.com/Rise-Vision/rise-data-financial/pull/106 and https://github.com/Rise-Vision/rise-init/pull/31
